### ISSUE TITLE
Notification payload schema not up to date

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/apidocs#23] opened 2015-07-04 20:11 UTC
Example:
http://developer.thegrid.io/schema/notification.json
`owner`, `repo`, `name` do not exist in the spec

``` javascript
[id: 94abb08d-6822-4a37-92b3-e23003e5f187, owner: 368c03f5-d778-420c-b14d-58fd788912e2, repo: the-domains/sandbox, type: new_site, name: sandbox, aps: {
    "content-available" = 1;
}]
```

**Comment by bergie** [comment] 2016-11-22 15:52
Dupe of #1

**Closed as completed by bergie** 2016-11-22 15:52 UTC
Labels: bug
